import { Product, Category, Store, Review, Order, Promotion } from './types';

export const PROMOTIONS: Promotion[] = [
  {
    id: 'promo-1',
    title: 'SEASONAL UP TO 50% OFF',
    subtitle: 'Vogue Essentials Summer Collection',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
    backgroundColor: '#f3f4f6',
    discountCode: 'SUMMER50',
    storeId: 's1'
  },
  {
    id: 'promo-2',
    title: 'NEW TECH CLEARANCE',
    subtitle: 'Gadgets that define your future',
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=1000&auto=format&fit=crop',
    backgroundColor: '#000000',
    discountCode: 'TECHVIBE',
    storeId: 's2'
  },
  {
    id: 'promo-3',
    title: 'FLAVOR FESTIVAL',
    subtitle: 'Buy 1 Get 1 on Artisanal Treats',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=1000&auto=format&fit=crop',
    backgroundColor: '#fffbeb',
    discountCode: 'FEAST',
    storeId: 's3'
  }
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Pakaian', icon: 'Shirt' },
  { id: '2', name: 'Elektronik', icon: 'Smartphone' },
  { id: '3', name: 'Rumah Tangga', icon: 'Home' },
  { id: '4', name: 'Kecantikan', icon: 'Sparkles' },
  { id: '5', name: 'Olahraga', icon: 'Dumbbell' },
  { id: '6', name: 'Makanan', icon: 'Utensils' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Minimalist White Sneakers',
    price: 89,
    description: 'Clean, classic sneakers that pair with anything. Made from premium vegan leather with a comfortable cushioned sole.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 124,
    isFeatured: true,
    storeId: 's1',
  },
  {
    id: 'p2',
    name: 'Ultra-Slim Wireless Earbuds',
    price: 129,
    description: 'Experience crystal clear sound with our latest noise-canceling technology. 30-hour battery life and ergonomic fit.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 89,
    isFeatured: true,
    storeId: 's2',
  },
  {
    id: 'p3',
    name: 'Ceramic Pour-Over Set',
    price: 45,
    description: 'Handcrafted ceramic dripper and server for the perfect morning coffee ritual. High-heat retention and elegant design.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1544350282-829dce49c388?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 56,
    storeId: 's5',
  },
  {
    id: 'p4',
    name: 'Organic Silk Night Cream',
    price: 65,
    description: 'Deeply hydrating night cream made with pure silk extracts and organic botanicals. Wake up with glowing, refreshed skin.',
    category: 'Kecantikan',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 210,
    storeId: 's1',
  },
  {
    id: 'p5',
    name: 'Graphite Tennis Racket',
    price: 210,
    description: 'Professional grade graphite racket for ultimate precision and power. Lightweight design with advanced vibration dampening.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1617083277666-4accce979313?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 42,
    storeId: 's4',
  },
  {
    id: 'p6',
    name: 'Tech-Knit Running Hoodie',
    price: 75,
    description: 'Breathable, moisture-wicking fabric with integrated reflective elements for safe night running. Ergonomic seams for maximum mobility.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 78,
    storeId: 's4',
  },
  // s1: Vogue Essentials (Pakaian)
  {
    id: 'p7',
    name: 'Classic Trench Coat',
    price: 199,
    description: 'A timeless staple for any wardrobe. Waterproof and elegantly tailored.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 45,
    storeId: 's1',
  },
  {
    id: 'p8',
    name: 'Silk Blouse',
    price: 85,
    description: 'Luxurious silk blouse with a smooth finish. Perfect for formal and casual wear.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 32,
    storeId: 's1',
  },
  {
    id: 'p9',
    name: 'Leather Handbag',
    price: 250,
    description: 'Genuine leather handbag with spacious compartments and premium hardware.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 67,
    storeId: 's1',
  },
  {
    id: 'p10',
    name: 'Denim Jacket',
    price: 120,
    description: 'Classic blue denim jacket with a vintage wash. Durable and stylish.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1544642899-f0d6e5f6ed6a?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 89,
    storeId: 's1',
  },
  {
    id: 'p11',
    name: 'Cashmere Sweater',
    price: 140,
    description: 'Ultra-soft cashmere sweater for ultimate warmth and comfort.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 24,
    storeId: 's1',
  },
  {
    id: 'p12',
    name: 'Pleated Skirt',
    price: 65,
    description: 'Elegant pleated skirt that moves beautifully. Great for any occasion.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 51,
    storeId: 's1',
  },
  {
    id: 'p13',
    name: 'Chelsea Boots',
    price: 180,
    description: 'Sleek leather Chelsea boots with an easy pull-on design.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 43,
    storeId: 's1',
  },
  {
    id: 'p14',
    name: 'Tailored Blazer',
    price: 160,
    description: 'Sharp tailored blazer for a professional look. High-quality fabric.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1591348115749-c19142ec4630?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 29,
    storeId: 's1',
  },
  {
    id: 'p15',
    name: 'Floral Maxi Dress',
    price: 95,
    description: 'Beautiful floral print maxi dress. Perfect for spring and summer.',
    category: 'Pakaian',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 72,
    storeId: 's1',
  },
  // s2: Tech Haven (Elektronik)
  {
    id: 'p16',
    name: 'Gaming Mouse',
    price: 79,
    description: 'High-precision gaming mouse with customizable RGB lighting.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3a70?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 156,
    storeId: 's2',
  },
  {
    id: 'p17',
    name: 'Mechanical Keyboard',
    price: 149,
    description: 'Tactile mechanical keyboard for ultimate typing and gaming experience.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 84,
    storeId: 's2',
  },
  {
    id: 'p18',
    name: '4K Monitor',
    price: 349,
    description: 'Stunning 4K resolution monitor for professional workflows and entertainment.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1527443195645-d13a303b13a8?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 62,
    storeId: 's2',
  },
  {
    id: 'p19',
    name: 'Noise Cancelling Headphones',
    price: 299,
    description: 'Immersive sound with industry-leading noise cancellation technology.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 320,
    storeId: 's2',
  },
  {
    id: 'p20',
    name: 'Smart Watch',
    price: 249,
    description: 'Track your fitness, notifications, and more from your wrist.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 110,
    storeId: 's2',
  },
  {
    id: 'p21',
    name: 'Wireless Charger',
    price: 39,
    description: 'Fast wireless charging for all your compatible devices.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1586816829380-60b69114f05b?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 95,
    storeId: 's2',
  },
  {
    id: 'p22',
    name: 'Portable SSD 1TB',
    price: 119,
    description: 'Compact and fast portable storage for your important files.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 76,
    storeId: 's2',
  },
  {
    id: 'p23',
    name: 'Tablet Pro',
    price: 799,
    description: 'Power through your tasks with our most advanced tablet.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 45,
    storeId: 's2',
  },
  {
    id: 'p24',
    name: 'Webcam HD',
    price: 89,
    description: 'Crystal clear HD video for all your meetings and streaming.',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83dadc?q=80&w=1000&auto=format&fit=crop',
    rating: 4.4,
    reviews: 130,
    storeId: 's2',
  },
  // s3: Gourmet Street (Makanan)
  {
    id: 'p25',
    name: 'Artisanal Dark Chocolate',
    price: 15,
    description: 'Small-batch dark chocolate with hints of sea salt and caramel.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 88,
    storeId: 's3',
  },
  {
    id: 'p26',
    name: 'Specialty Coffee Beans',
    price: 22,
    description: 'Ethically sourced, single-origin coffee beans roasted to perfection.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 120,
    storeId: 's3',
  },
  {
    id: 'p27',
    name: 'Gourmet Truffle Oil',
    price: 35,
    description: 'Infuse your dishes with the rich, earthy aroma of white truffles.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1589113264426-edbc14c44243?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 45,
    storeId: 's3',
  },
  {
    id: 'p28',
    name: 'Organic Honey',
    price: 18,
    description: 'Pure, raw organic honey harvested from wildflower fields.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 150,
    storeId: 's3',
  },
  {
    id: 'p29',
    name: 'Assorted Macarons',
    price: 28,
    description: 'A colorful box of delicate French macarons in various flavors.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 92,
    storeId: 's3',
  },
  {
    id: 'p30',
    name: 'Aged Balsamic Vinegar',
    price: 42,
    description: 'Authentic balsamic vinegar aged in oak barrels for deep flavor.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1590540179852-2110a54f813a?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 34,
    storeId: 's3',
  },
  {
    id: 'p31',
    name: 'Himalayan Pink Salt',
    price: 12,
    description: 'Natural, mineral-rich pink salt for all your culinary needs.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 210,
    storeId: 's3',
  },
  {
    id: 'p32',
    name: 'Matcha Powder Premium',
    price: 25,
    description: 'Ceremonial grade matcha powder for a traditional tea experience.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1582793988951-9aed55099991?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 65,
    storeId: 's3',
  },
  {
    id: 'p33',
    name: 'Spiced Chai Mix',
    price: 14,
    description: 'A warming blend of black tea and aromatic spices.',
    category: 'Makanan',
    image: 'https://images.unsplash.com/photo-1576092762791-dd9e2220abd1?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 48,
    storeId: 's3',
  },
  // s4: Urban Sport (Olahraga)
  {
    id: 'p34',
    name: 'Yoga Mat Premium',
    price: 45,
    description: 'Non-slip yoga mat with extra cushioning for comfort and stability.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1592432676556-28456cc3cb45?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 132,
    storeId: 's4',
  },
  {
    id: 'p35',
    name: 'Adjustable Dumbbells',
    price: 159,
    description: 'Space-saving adjustable dumbbells for a versatile home workout.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 58,
    storeId: 's4',
  },
  {
    id: 'p36',
    name: 'Resistance Bands Set',
    price: 25,
    description: 'Set of multi-level resistance bands for full-body conditioning.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1598289439248-05227443105a?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 240,
    storeId: 's4',
  },
  {
    id: 'p37',
    name: 'Cycling Helmet',
    price: 85,
    description: 'Lightweight and aerodynamic cycling helmet with superior ventilation.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1557161181-bdb49742468d?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 42,
    storeId: 's4',
  },
  {
    id: 'p38',
    name: 'Basketball Pro',
    price: 40,
    description: 'Official size and weight basketball for indoor and outdoor play.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1519861155730-0b5fbf0dd889?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 115,
    storeId: 's4',
  },
  {
    id: 'p39',
    name: 'Performance Running Shoes',
    price: 130,
    description: 'Engineered for speed and comfort over any distance.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 198,
    storeId: 's4',
  },
  {
    id: 'p40',
    name: 'Swim Goggles',
    price: 20,
    description: 'Anti-fog swim goggles with a comfortable watertight fit.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1551698618-1fed5d96559e?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 87,
    storeId: 's4',
  },
  {
    id: 'p41',
    name: 'Hydration Pack',
    price: 65,
    description: 'Ergonomic hydration pack for hiking and trail running.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1559311648-d46f4d8593d8?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 53,
    storeId: 's4',
  },
  {
    id: 'p42',
    name: 'Gym Duffel Bag',
    price: 55,
    description: 'Spacious gym bag with separate shoe compartment and multiple pockets.',
    category: 'Olahraga',
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 74,
    storeId: 's4',
  },
  // s5: Zen Living (Rumah Tangga)
  {
    id: 'p43',
    name: 'Scented Soy Candle',
    price: 24,
    description: 'Hand-poured soy candle with calming lavender and white tea notes.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1603006905393-c917ed66347a?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 145,
    storeId: 's5',
  },
  {
    id: 'p44',
    name: 'Linen Bedding Set',
    price: 180,
    description: 'Premium linen bedding set for a breathable and luxurious sleep.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 32,
    storeId: 's5',
  },
  {
    id: 'p45',
    name: 'Abstract Wall Art',
    price: 90,
    description: 'Minimalist abstract wall art to bring character to your space.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 28,
    storeId: 's5',
  },
  {
    id: 'p46',
    name: 'Indoor Planter',
    price: 35,
    description: 'Stylish ceramic indoor planter with a bamboo stand.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    reviews: 95,
    storeId: 's5',
  },
  {
    id: 'p47',
    name: 'Bamboo Towel Set',
    price: 45,
    description: 'Eco-friendly bamboo towel set, ultra-absorbent and soft.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1563842187313-5a7a72d32512?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    reviews: 64,
    storeId: 's5',
  },
  {
    id: 'p48',
    name: 'Essential Oil Diffuser',
    price: 50,
    description: 'Ultrasonic diffuser with LED lighting for a sensory home experience.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    reviews: 110,
    storeId: 's5',
  },
  {
    id: 'p49',
    name: 'Throw Blanket',
    price: 60,
    description: 'Soft and cozy throw blanket to keep you warm on chilly nights.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1580302200234-709088561845?q=80&w=1000&auto=format&fit=crop',
    rating: 4.5,
    reviews: 156,
    storeId: 's5',
  },
  {
    id: 'p50',
    name: 'Minimalist Wall Clock',
    price: 40,
    description: 'Simple and elegant wall clock with a silent sweeping movement.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?q=80&w=1000&auto=format&fit=crop',
    rating: 4.4,
    reviews: 42,
    storeId: 's5',
  },
  {
    id: 'p51',
    name: 'Glass Carafe Set',
    price: 30,
    description: 'Elegant glass carafe and tumblers for serving beverages.',
    category: 'Rumah Tangga',
    image: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    reviews: 59,
    storeId: 's5',
  },
];

export const STORES: Store[] = [
  {
    id: 's1',
    name: 'Vogue Essentials',
    category: 'Fashion',
    description: 'High-end designer labels and contemporary streetwear.',
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    location: { lat: -6.2238, lng: 106.8041 }
  },
  {
    id: 's2',
    name: 'Tech Haven',
    category: 'Electronics',
    description: 'The latest gadgets, components, and smart home solutions.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000&auto=format&fit=crop',
    rating: 4.7,
    location: { lat: -6.2245, lng: 106.8095 }
  },
  {
    id: 's3',
    name: 'Gourmet Street',
    category: 'Food',
    description: 'Artisanal snacks, premium coffee, and international delicacies.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1000&auto=format&fit=crop',
    rating: 4.8,
    location: { lat: -6.2255, lng: 106.8055 }
  },
  {
    id: 's4',
    name: 'Urban Sport',
    category: 'Sports',
    description: 'Professional gear for every athlete and fitness enthusiast.',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000&auto=format&fit=crop',
    rating: 4.6,
    location: { lat: -6.2225, lng: 106.8075 }
  },
  {
    id: 's5',
    name: 'Zen Living',
    category: 'Home',
    description: 'Minimalist furniture and home accessories for a peaceful life.',
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1000&auto=format&fit=crop',
    rating: 4.9,
    location: { lat: -6.2268, lng: 106.8081 }
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    productId: 'p1',
    userName: 'Andi Pratama',
    rating: 5,
    comment: 'Sepatunya sangat nyaman dan desainnya sangat minimalis. Suka sekali!',
    date: '2024-05-15',
  },
  {
    id: 'r2',
    productId: 'p1',
    userName: 'Siti Aminah',
    rating: 4,
    comment: 'Bagus, tapi ukurannya sedikit lebih besar dari biasanya.',
    date: '2024-05-10',
  },
  {
    id: 'r3',
    productId: 'p2',
    userName: 'Budi Santoso',
    rating: 5,
    comment: 'Kualitas suara luar biasa untuk harga segini. Noise canceling bekerja dengan baik.',
    date: '2024-05-18',
  }
];

export const ORDERS: Order[] = [
  {
    id: 'ORD-8821',
    date: '2024-05-20',
    status: 'In Transit',
    total: 218,
    items: [
      {
        productId: 'p1',
        name: 'Minimalist White Sneakers',
        price: 89,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop',
      },
      {
        productId: 'p2',
        name: 'Ultra-Slim Wireless Earbuds',
        price: 129,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop',
      }
    ],
    trackingNumber: 'JKT-992200331',
    shippingAddress: 'Jl. Sudirman No. 12, Jakarta Selatan'
  },
  {
    id: 'ORD-7542',
    date: '2024-05-10',
    status: 'Delivered',
    total: 45,
    items: [
      {
        productId: 'p3',
        name: 'Ceramic Pour-Over Set',
        price: 45,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1544350282-829dce49c388?q=80&w=1000&auto=format&fit=crop',
      }
    ],
    shippingAddress: 'Apartemen Green Pramuka, Jakarta Pusat'
  }
];
